name: estate_market
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_platform_widgets: ^6.0.0

  domain:
    path: domain

  data:
    path: data

  core:
    path: core

  gem_kit:
    path: plugins/gem_kit
    
  bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: any
  cloud_firestore: ^4.16.0
  firebase_core: ^2.24.0
  get_it: ^7.6.4
  dartz: ^0.10.1
  image_picker: ^1.0.7
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.5.0
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  url_launcher: ^6.2.6
  network_discovery: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
