name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  build_runner: ^2.4.9
  dartz: ^0.10.1
  equatable: ^2.0.5
  mockito: ^5.4.4
  rxdart: ^0.27.7
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
