// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8zfAt3llCYxYPmsWZdsAYd7Lzx7Q776c',
    appId: '1:1097147651983:web:32fb83fcc19634457d9dfa',
    messagingSenderId: '1097147651983',
    projectId: 'estatemarket-2cbc4',
    authDomain: 'estatemarket-2cbc4.firebaseapp.com',
    storageBucket: 'estatemarket-2cbc4.appspot.com',
    measurementId: 'G-W3LV6P2758',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp9iIa1rU7_iX9DndySmLk-OOGSB0u_LI',
    appId: '1:1097147651983:android:622792dc23f05ac67d9dfa',
    messagingSenderId: '1097147651983',
    projectId: 'estatemarket-2cbc4',
    storageBucket: 'estatemarket-2cbc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClrywGlP8do-kAFzVlivq_TlqZuUMcFCY',
    appId: '1:1097147651983:ios:8cf7818b5d2fc6807d9dfa',
    messagingSenderId: '1097147651983',
    projectId: 'estatemarket-2cbc4',
    storageBucket: 'estatemarket-2cbc4.appspot.com',
    iosBundleId: 'com.example.estateMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClrywGlP8do-kAFzVlivq_TlqZuUMcFCY',
    appId: '1:1097147651983:ios:0ab0a79e393914d17d9dfa',
    messagingSenderId: '1097147651983',
    projectId: 'estatemarket-2cbc4',
    storageBucket: 'estatemarket-2cbc4.appspot.com',
    iosBundleId: 'com.example.estateMarket.RunnerTests',
  );
}
